variables:
  IMAGE_REPO_NAME: "helloworld"
  IMAGE_TAG: "latest"
  AWS_DEFAULT_REGION: "ap-northeast-1"
  AWS_ACCOUNT_ID: "885743098742"
  DOCKER_HOST: "tcp://docker:2375"
stages:
  - publish
  - push-image-gitlab
publish:
  stage: publish
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $IMAGE_REPO_NAME:$CI_JOB_ID .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - docker tag $IMAGE_REPO_NAME:$CI_JOB_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CI_JOB_ID
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CI_JOB_ID

